import { Header } from '@/components';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/styles.scss';
import { TransactionContextProvider } from '@/hooks/useTransaction';
import { loadTransactions } from '@/services/loadTransactions';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const storedTransactions = await loadTransactions();
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransactionContextProvider storedTransactions={storedTransactions}>
          <Header />
          {children}
        </TransactionContextProvider>
      </body>
    </html>
  )
}
